(function(){
  'use strict';
  const C=window.ULTRACore;
  if(!C){document.body.innerHTML='<main style="font-family:system-ui;padding:32px"><h1>ULTRA BASE</h1><p>Falha ao carregar o motor. Atualize a página.</p></main>';return;}
  const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const MEMORY_KEY='ultra-base-v5.2-memory';
  const ANALYSES_KEY='ultra-base-v5.2-analyses';
  const MSG_KEY='ultra-base-v5.2-messages';
  let memory=loadJSON(MEMORY_KEY,C.newMemory()), analyses=loadJSON(ANALYSES_KEY,[]), messages=loadJSON(MSG_KEY,[]), baseMode='facts',milenaMode='visao',templates=C.TEMPLATES.slice();
  const titles={copiloto:'Copiloto',inteligencia:'Inteligência',milena:'Milena',base:'Base'};
  const templateGroups={INICIO_CONVERSA:'Início de conversa',MARKETING:'Marketing digital',FOLLOW_UP:'Follow-up',REAGENDAMENTO:'Reagendamento'};
  const goalLabels={CONVERSAO:'Conversão',HUMANIZACAO:'Humanização',EDUCACAO:'Educação'};

  function loadJSON(k,f){try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}}
  function saveJSON(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
  function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__ut);window.__ut=setTimeout(()=>t.classList.remove('show'),1900)}
  function go(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if($('#pageTitle'))$('#pageTitle').textContent=titles[view]||'ULTRA BASE';const sb=$('.sidebar');if(sb)sb.classList.remove('open');if(view==='inteligencia')renderIntelligence();if(view==='milena')renderMilena();if(view==='base')renderBase();}
  async function copy(text){try{await navigator.clipboard.writeText(text);toast('Copiado.')}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('Copiado.')}}
  function persistMemory(){saveJSON(MEMORY_KEY,memory)}
  function clearComposer(){if($('#patientText')){$('#patientText').value='';$('#patientText').focus()}toast('Campo limpo. O contexto foi mantido.')}
  function nextMessage(){clearComposer();renderMemoryPanel();toast('Pronta para a próxima mensagem deste mesmo paciente.')}
  function newConversation(){if(!window.confirm('Iniciar uma nova conversa?\nO contexto atual será encerrado.'))return;memory=C.newMemory();persistMemory();if($('#patientText'))$('#patientText').value='';if($('#patientName'))$('#patientName').value='';$('#copilotResult').innerHTML='<div class="empty-state"><div class="spark">✦</div><strong>Nova conversa iniciada.</strong><p>O contexto anterior foi encerrado.</p></div>';renderMemoryPanel();toast('Nova conversa iniciada.')}

  function runAnalysis(){
    const text=($('#patientText')?.value||'').trim(); if(!text){toast('Escreva a fala da pessoa.');$('#patientText')?.focus();return;}
    try{
      const a=C.analyze(text,{name:$('#patientName')?.value||'',agent:$('#agentName')?.value||'',memory});
      memory=C.observePatient(memory,a); memory=C.recordSuggestions(memory,a); persistMemory();
      analyses.unshift(a); analyses=analyses.slice(0,500); saveJSON(ANALYSES_KEY,analyses); renderResult(a);renderMemoryPanel();
    }catch(err){console.error(err);$('#copilotResult').innerHTML='<div class="warning-box"><strong>Não consegui gerar a orientação.</strong><p>Atualize a página e tente novamente. O erro foi registrado no console do navegador.</p></div>';toast('Falha ao analisar.');}
  }

  function renderResult(a){
    const sec=(a.secondaryIntents||[]).map(x=>x.label).join(' · ');
    $('#copilotResult').innerHTML=`<div class="result-top"><div><span class="intent-pill">${esc(a.intentLabel)}</span><div class="confidence">Confiança: ${esc(a.confidence)} · Estado: ${esc(a.state)}</div>${sec?`<div class="secondary">Contexto secundário: ${esc(sec)}</div>`:''}</div></div>
    <div class="suggestion-block"><div class="suggestion-head"><h3>Resposta sugerida</h3><span>Sugestão ≠ enviada</span></div><textarea id="answerDraft" class="suggestion-editor" rows="5">${esc(a.answer)}</textarea><div class="suggestion-actions"><button class="secondary" id="copyAnswer">Copiar</button><button class="primary" id="markAnswerSent">Marcar resposta como enviada</button></div></div>
    ${a.question?`<div class="suggestion-block question-block"><div class="suggestion-head"><h3>Pergunta sugerida</h3><span>Só entra no histórico se você confirmar</span></div><textarea id="questionDraft" class="suggestion-editor" rows="3">${esc(a.question)}</textarea><div class="suggestion-actions"><button class="secondary" id="copyQuestion">Copiar</button><button class="primary" id="markQuestionSent">Marcar pergunta como enviada</button></div></div>`:''}
    <div class="action-card"><div class="micro-card"><span>Próxima melhor ação</span><strong>${esc(a.action)}</strong><button class="ghost action-confirm" id="confirmSuggestedAction">Registrar ação realizada</button></div><div class="micro-card"><span>Registrar no RD</span><strong>${esc(a.register)}</strong></div></div>
    ${a.safety?.length?`<div class="warning-box"><strong>Atenção</strong><p>${esc(a.safety.join(' '))}</p></div>`:''}
    <details class="details"><summary>Ver leitura do atendimento</summary><div class="detail-grid"><div class="detail-item"><span>Quem é o paciente</span><p>${esc(a.context.relationship?`Familiar/terceiro: ${a.context.patientRole}`:'Próprio ou ainda não definido')}</p></div><div class="detail-item"><span>O que já sabemos</span><p>${esc(a.known.join(' ')||'Ainda há pouco contexto declarado.')}</p></div><div class="detail-item"><span>Hipóteses da IA</span><p>${esc((a.context.inferences||[]).join(' ')||'Nenhuma inferência relevante.')}</p></div><div class="detail-item"><span>O que falta saber</span><p>${esc(a.unknowns.join(' ')||'Nenhuma lacuna crítica identificada.')}</p></div><div class="detail-item"><span>Fonte</span><p>${esc(a.source)}</p></div></div></details>`;
    $('#copyAnswer').onclick=()=>copy($('#answerDraft').value);
    $('#markAnswerSent').onclick=()=>{memory=C.confirmAnswer(memory,$('#answerDraft').value);persistMemory();renderMemoryPanel();toast('Resposta real registrada.')};
    if($('#copyQuestion'))$('#copyQuestion').onclick=()=>copy($('#questionDraft').value);
    if($('#markQuestionSent'))$('#markQuestionSent').onclick=()=>{memory=C.confirmQuestion(memory,$('#questionDraft').value);persistMemory();renderMemoryPanel();toast('Pergunta real registrada.')};
    $('#confirmSuggestedAction').onclick=()=>{memory=C.confirmAction(memory,a.action);persistMemory();renderMemoryPanel();toast('Ação confirmada.')};
  }

  function renderMemoryPanel(){const b=$('#conversationContext');if(!b)return;const line=(l,a)=>a&&a.length?`<div class="memory-row"><span>${l}</span><p>${a.slice(-6).map(x=>esc(typeof x==='string'?x:(x.raw||x.action||x.type||''))).join(' · ')}</p></div>`:'';b.innerHTML=`<div class="memory-head"><div><span class="eyebrow orange">CONTEXTO DESTA CONVERSA</span><strong>${memory.turns.length?`${memory.turns.length} evento(s) reais registrados`:'Ainda sem histórico real'}</strong></div><span class="memory-rule">Análise não é evento · sugestão não é ação</span></div>${line('Fatos confirmados',memory.observedFacts)}${line('Motivação',memory.motivations)}${line('Barreira',memory.barriers)}${line('Compromissos',memory.commitments)}${line('Perguntas já enviadas',memory.askedQuestions)}${!memory.turns.length?'<p class="muted">A memória começa com mensagens reais. Sugestões só viram histórico quando confirmadas.</p>':''}`}

  function currentItems(){return messages.length?messages:analyses.map(a=>({text:a.raw,agent:a.agent||'Não identificado',analysis:a,author:'patient'}));}
  function summary(items){const intents={},agents={},phrases={};let generic=0,long=0,early=0;for(const x of items){const a=x.analysis||C.analyze(x.text||'',{});intents[a.intentLabel]=(intents[a.intentLabel]||0)+1;if(x.agent)agents[x.agent]=(agents[x.agent]||0)+1;const t=(x.text||'').trim();if(t){const k=t.toLowerCase();phrases[k]=(phrases[k]||0)+1;if(/ainda tem interesse|conseguiu ver|podemos dar continuidade/.test(k))generic++;if(t.length>450)long++;if(/quer agendar|vamos agendar/.test(k)&&['HELLO','AMBIGUOUS'].includes(a.intent))early++;}}
    const top=o=>Object.entries(o).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([label,value])=>({label,value}));return {total:items.length,intents:top(intents),agents:top(agents),phrases:top(phrases).filter(x=>x.value>1),issues:[generic?{title:'Follow-up genérico',count:generic,why:'Retomar o contexto real tende a ser mais útil do que mensagens vazias.'}:null,long?{title:'Mensagens longas',count:long,why:'WhatsApp pede clareza e poucos pontos por vez.'}:null,early?{title:'Agenda cedo demais',count:early,why:'Entender a necessidade antes de pedir agenda evita pressão prematura.'}:null].filter(Boolean)};}
  function list(items){return items.length?`<div class="list-clean">${items.map(x=>`<div><span>${esc(x.label)}</span><strong>${x.value}</strong></div>`).join('')}</div>`:'<p class="muted">Ainda sem amostra suficiente.</p>'}
  function renderIntelligence(){const s=summary(currentItems());$('#intelligenceGrid').innerHTML=`<article class="insight-card"><span class="eyebrow">AMOSTRA</span><div class="big">${s.total}</div><p>interações analisadas neste navegador.</p></article><article class="insight-card"><span class="eyebrow">ASSUNTOS</span><h3>O que mais aparece</h3>${list(s.intents)}</article><article class="insight-card"><span class="eyebrow">FRASES REPETIDAS</span><h3>O que mais se repete</h3>${list(s.phrases)}</article>${s.issues.slice(0,3).map(i=>`<article class="insight-card"><span class="eyebrow">OPORTUNIDADE</span><div class="big">${i.count}</div><h3>${esc(i.title)}</h3><p>${esc(i.why)}</p></article>`).join('')}`}

  function getStatus(id,def){return localStorage.getItem(`ultra-template-status:${id}`)||def}
  function templateCard(t){return `<article class="template-card"><div class="template-card-top"><span class="goal goal-${t.goal.toLowerCase()}">${esc(goalLabels[t.goal])}</span><span class="meta-badge">${esc(t.meta_category)}</span></div><h4>${esc(t.name_rd)}</h4><p class="template-copy">${esc(t.text)}</p><div class="template-meta"><span>Quando usar</span><p>${esc(t.when_to_use)}</p></div><div class="template-actions"><button class="secondary" data-copy-template="${t.id}">Copiar texto</button><button class="ghost" data-open-template="${t.id}">Ver detalhes</button></div><label class="status-control">Status <select data-template-status="${t.id}">${['DRAFT','REVIEWED','READY_FOR_RD','SUBMITTED','META_APPROVED','META_REJECTED','ACTIVE','ARCHIVED'].map(x=>`<option ${x===getStatus(t.id,t.status)?'selected':''}>${x}</option>`).join('')}</select></label></article>`}
  function renderTemplates(){return `<div class="template-toolbar"><div><strong>12 templates oficiais</strong><span>Conversão, humanização e educação.</span></div><p>Confirme a categoria final no RD/Meta antes de ativar.</p></div>${Object.keys(templateGroups).map(g=>`<section class="template-group"><div class="section-head"><div><span class="eyebrow orange">${esc(templateGroups[g])}</span><h3>${esc(templateGroups[g])}</h3></div></div><div class="template-grid">${templates.filter(t=>t.group===g).map(templateCard).join('')}</div></section>`).join('')}`}
  function bindTemplates(){$$('[data-copy-template]').forEach(b=>b.onclick=()=>{const t=templates.find(x=>x.id===b.dataset.copyTemplate);if(t)copy(t.text)});$$('[data-open-template]').forEach(b=>b.onclick=()=>openTemplate(b.dataset.openTemplate));$$('[data-template-status]').forEach(s=>s.onchange=()=>{localStorage.setItem(`ultra-template-status:${s.dataset.templateStatus}`,s.value);toast('Status atualizado.')})}
  function openTemplate(id){const t=templates.find(x=>x.id===id);if(!t)return;$('#templateModalContent').innerHTML=`<span class="eyebrow orange">${esc(templateGroups[t.group])} · ${esc(goalLabels[t.goal])}</span><h2 id="templateModalTitle">${esc(t.name_rd)}</h2><div class="modal-copy">${esc(t.text)}</div><div class="modal-grid"><div><span>Categoria sugerida</span><strong>${esc(t.meta_category)}</strong></div><div><span>Próxima ação</span><strong>${esc(t.next_best_action)}</strong></div><div><span>Variáveis</span><strong>${esc(t.variables.join(' · '))}</strong></div><div><span>Quando não usar</span><strong>${esc(t.when_not_to_use)}</strong></div></div><div class="modal-actions"><button class="primary" id="modalCopyText">Copiar texto</button><button class="secondary" id="modalCopyName">Copiar nome RD</button></div>`;$('#templateModal').classList.add('open');$('#templateModal').setAttribute('aria-hidden','false');$('#modalCopyText').onclick=()=>copy(t.text);$('#modalCopyName').onclick=()=>copy(t.name_rd)}
  function closeTemplate(){$('#templateModal').classList.remove('open');$('#templateModal').setAttribute('aria-hidden','true')}
  function renderMilena(){const s=summary(currentItems()),prior=s.issues.length?s.issues:[{title:'Ainda sem padrão negativo suficiente',count:0,why:'Use o Copiloto ou importe conversas para formar uma amostra real.'}];if(milenaMode==='templates'){$('#milenaPanel').innerHTML=renderTemplates();bindTemplates();return;}if(milenaMode==='atendentes'){$('#milenaPanel').innerHTML=`<article class="coach-card"><span class="eyebrow orange">ATENDENTES</span><h3>Onde a Milena deve olhar</h3>${s.agents.length?s.agents.map(a=>`<div class="person-row"><strong>${esc(a.label)}</strong><p>${a.value} registro(s) na amostra. A qualidade só deve ser julgada com contexto real.</p></div>`).join(''):'<p class="muted">Ainda não existe autoria suficiente para leitura individual.</p>'}</article>`;return;}$('#milenaPanel').innerHTML=`<article class="milena-hero"><span class="eyebrow">LEITURA GERENCIAL</span><h3>${s.total?`Há ${s.total} interações disponíveis para aprender.`:'Comece pelo comportamento, não pelo volume.'}</h3><p>A ULTRA BASE complementa o RD com inteligência sobre qualidade das conversas.</p></article><div class="milena-grid"><article class="coach-card"><span class="eyebrow orange">O QUE MELHORAR</span><h3>Prioridades de coaching</h3><div class="priority-list">${prior.slice(0,5).map((p,i)=>`<div class="priority-item"><div class="priority-number">${i+1}</div><div><h4>${esc(p.title)}${p.count?` · ${p.count} caso(s)`:''}</h4><p>${esc(p.why)}</p></div></div>`).join('')}</div></article><article class="coach-card"><span class="eyebrow orange">TREINO DA SEMANA</span><h3>${esc(prior[0].title)}</h3><p>${esc(prior[0].why)}</p><div class="training-rule">Reconhecer contexto → responder → fazer uma pergunta útil → deixar o próximo passo claro.</div></article></div>`}

  function baseItems(){const q=($('#baseSearch')?.value||'').toLowerCase();if(baseMode==='facts')return C.FACTS.filter(x=>JSON.stringify(x).toLowerCase().includes(q)).map(x=>({title:x.q,text:x.answer,source:x.source,tag:x.status==='CONFIRMADO'?'Confirmado':x.status}));if(baseMode==='faq')return C.FAQ.filter(x=>JSON.stringify(x).toLowerCase().includes(q)).map(x=>({title:x.title,text:x.answer,source:x.limit?'Exige limite clínico quando individualizado':'Informação geral segura',tag:x.limit?'Limite clínico':'Conhecimento'}));return [{title:'Método ULTRA',text:'Ouvir → entender → refletir → aprofundar → orientar → trabalhar barreira → testar prontidão → conduzir → registrar → retomar.',source:'Método ULTRA',tag:'Cenário'}];}
  function renderBase(){const items=baseItems();$('#baseContent').innerHTML=`<div class="knowledge-grid">${items.map(x=>`<article class="knowledge-card"><span class="tag ${x.tag==='Confirmado'?'safe':x.tag==='Limite clínico'?'limit':''}">${esc(x.tag)}</span><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p><div class="source">${esc(x.source)}</div></article>`).join('')||'<p class="muted">Nada encontrado.</p>'}</div>`}

  function importConversations(file){const r=new FileReader();r.onload=()=>{try{const p=C.parseCSV(String(r.result||''));if(!p.rows.length){toast('CSV sem registros.');return;}const g=C.guess(p.headers);const msg=g.message||p.headers[0];messages=p.rows.map((row,i)=>({id:`msg-${Date.now()}-${i}`,text:row[msg]||'',agent:g.agent?row[g.agent]||'':'',author:g.author?row[g.author]||'':'',date:g.date?row[g.date]||'':''})).filter(x=>x.text.trim()).slice(0,5000);saveJSON(MSG_KEY,messages);toast(`${messages.length} mensagens importadas.`);go('inteligencia');}catch(e){console.error(e);toast('Não consegui ler esse CSV.')}};r.readAsText(file);}

  function cleanupLegacy(){try{if('serviceWorker'in navigator)navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister()));if('caches'in window)caches.keys().then(keys=>keys.filter(k=>k.startsWith('ultra-base-')).forEach(k=>caches.delete(k)));}catch{}}
  function bind(){
    $$('#nav [data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');$('#analyzeBtn').onclick=runAnalysis;$('#patientText').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')runAnalysis()});$$('[data-example]').forEach(b=>b.onclick=()=>{$('#patientText').value=b.dataset.example;runAnalysis()});$('#clearComposerBtn').onclick=clearComposer;$('#nextMessageBtn').onclick=nextMessage;$('#newConversationBtn').onclick=newConversation;$('#conversationFile').onchange=e=>e.target.files[0]&&importConversations(e.target.files[0]);$$('[data-base]').forEach(b=>b.onclick=()=>{baseMode=b.dataset.base;$$('[data-base]').forEach(x=>x.classList.toggle('active',x===b));renderBase()});$('#baseSearch').oninput=renderBase;$$('[data-milena]').forEach(b=>b.onclick=()=>{milenaMode=b.dataset.milena;$$('[data-milena]').forEach(x=>x.classList.toggle('active',x===b));renderMilena()});$('#templateModalClose').onclick=closeTemplate;$('#templateModal').onclick=e=>{if(e.target.id==='templateModal')closeTemplate()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeTemplate()});
  }
  function boot(){try{cleanupLegacy();bind();renderMemoryPanel();renderIntelligence();renderMilena();renderBase();document.documentElement.dataset.ultraReady='true';}catch(e){console.error('ULTRA BASE boot error',e);const r=$('#copilotResult');if(r)r.innerHTML='<div class="warning-box"><strong>Falha ao iniciar a ULTRA BASE.</strong><p>Recarregue a página. Se persistir, envie uma captura do console técnico.</p></div>';}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
