import {normalize,includesAny,similarity} from './normalizer.js';
import {ULTRA_FACTS} from '../data/ultra-facts.js';
import {FAQ} from '../data/knowledge.js';

const INTENTS=[
{id:'urgent',label:'Atenção clínica',weight:100,terms:['sangrando muito','sangramento forte','falta de ar','febre','inchaço forte','inchaco forte','reação medicamento','reacao medicamento','desmaio','dor insuportável','dor insuportavel']},
{id:'address',label:'Informação da clínica',weight:95,terms:['endereco','onde fica','como chegar','localizacao']},
{id:'hours',label:'Informação da clínica',weight:95,terms:['horario','abre sabado','abre sábado','que horas abre','que horas fecha','funciona sabado','funciona sábado']},
{id:'whatsapp',label:'Informação da clínica',weight:95,terms:['whatsapp','telefone','numero de contato','número de contato']},
{id:'insurance',label:'Informação comercial',weight:92,terms:['convenio','convênio','plano odontologico','plano odontológico']},
{id:'schedule',label:'Pronto para agendar',weight:90,terms:['quero marcar','quero agendar','tem horario','tem horário','agenda','marcar avaliacao','marcar avaliação','qual dia tem']},
{id:'reschedule',label:'Remarcação',weight:90,terms:['remarcar','mudar horario','mudar horário','cancelar consulta','outra data']},
{id:'noshow',label:'Recuperação de falta',weight:88,terms:['nao fui','não fui','faltei','perdi a consulta','nao consegui ir']},
{id:'price-block',label:'Objeção de preço',weight:88,terms:['achei caro','muito caro','valor alto','nao tenho dinheiro','não tenho dinheiro','fora do meu orçamento']},
{id:'price',label:'Pergunta de preço',weight:86,terms:['quanto custa','qual valor','preco','preço','quanto fica','quanto sai']},
{id:'fear',label:'Medo / insegurança',weight:85,terms:['medo','receio','pavor','anestesia','trauma','cirurgia horrivel','cirurgia horrível']},
{id:'bone',label:'Pouco osso',weight:84,terms:['pouco osso','sem osso','nao tenho osso','não tenho osso','perda ossea','perda óssea','zigomatico','zigomático']},
{id:'family',label:'Decisão compartilhada',weight:82,terms:['minha filha','meu filho','minha esposa','meu marido','minha mae','minha mãe','meu pai','familia','família','conversar com']},
{id:'think',label:'Adiamento',weight:80,terms:['vou pensar','quero pensar','agora nao','agora não','mais pra frente','me chama mes que vem','me chama mês que vem']},
{id:'comparison',label:'Comparação',weight:80,terms:['outra clinica','outra clínica','mais barato','outro orçamento','outro orcamento']},
{id:'post-eval',label:'Pós-avaliação',weight:80,terms:['ja passei na avaliacao','já passei na avaliação','fiz avaliacao','fiz avaliação','orcamento que recebi','orçamento que recebi']},
{id:'prosthesis',label:'Uso de prótese',weight:78,terms:['dentadura','protese removivel','prótese removível','chapa','protocolo']},
{id:'one-tooth',label:'Perda de um dente',weight:76,terms:['perdi um dente','falta um dente','um dente perdido']},
{id:'many-teeth',label:'Perda de vários dentes',weight:76,terms:['perdi varios dentes','perdi vários dentes','faltam varios dentes','faltam vários dentes','muitos dentes']},
{id:'clinical',label:'Dúvida clínica',weight:70,terms:['posso fazer','isso e normal','isso é normal','tenho diabetes','marevan','anticoagulante','implante doi','implante dói','faceta','clareamento','carga imediata','rejeita','rejeicao','rejeição']},
{id:'hello',label:'Primeiro contato',weight:60,terms:['oi','ola','olá','bom dia','boa tarde','boa noite']}
];

function intentScore(text,rule){const n=normalize(text);let s=0;for(const term of rule.terms){const t=normalize(term);if(n===t)s+=12;else if(n.includes(t))s+=8;else s+=similarity(n,t)*2;}return s+rule.weight/100}
export function routeIntent(text){const scored=INTENTS.map(r=>({...r,score:intentScore(text,r)})).sort((a,b)=>b.score-a.score);const best=scored[0];if(!best||best.score<2)return {id:'unknown',label:'Precisa de contexto',confidence:'baixa',alternatives:scored.slice(0,2)};return {...best,confidence:best.score>8?'forte':best.score>4?'provável':'moderada',alternatives:scored.slice(1,3)}}

function factMatch(text){return ULTRA_FACTS.map(f=>({...f,score:f.keywords.reduce((s,k)=>s+(includesAny(text,[k])?4:0),0)})).sort((a,b)=>b.score-a.score)[0]}
function faqMatch(text){return FAQ.map(f=>({...f,score:f.keywords.reduce((s,k)=>s+(includesAny(text,[k])?4:0),0)+similarity(text,f.title)})).sort((a,b)=>b.score-a.score)[0]}
function firstName(name){return String(name||'').trim().split(/\s+/)[0]||''}
const greet=(name)=>name?`${firstName(name)}, `:'';

function scenarioResponse(intent,text,name){const g=greet(name);const n=normalize(text);
 switch(intent.id){
  case 'urgent': return {answer:`${g}esse relato precisa de atenção clínica agora. Entre em contato direto com a equipe responsável. Se houver falta de ar, sangramento intenso, desmaio ou piora rápida, procure atendimento de urgência.`,question:'Não prolongue a conversa comercial.',action:'ESCALAR CLÍNICO / URGÊNCIA',register:'Registrar o relato e o encaminhamento realizado.',risk:true};
  case 'address': case 'hours': case 'whatsapp': case 'insurance': {const f=factMatch(text);return {answer:f?.answer||'Vou usar apenas uma informação institucional confirmada pela Ultra.',question:'',action:'RESPONDER',register:'Não exige tarefa apenas por esta pergunta.',source:f?.source};}
  case 'schedule': return {answer:`${g}claro. Vou te ajudar a avançar com a avaliação.`,question:'Qual período costuma funcionar melhor para você: manhã ou tarde?',action:'AGENDAR',register:'Registrar intenção de agendamento e a opção de período.',state:'PRONTO_PARA_AGENDAR'};
  case 'reschedule': return {answer:`${g}sem problema. Vamos encontrar uma nova opção que realmente funcione para você.`,question:'O que fica melhor agora: outro dia ou outro período?',action:'REMARCAR',register:'Registrar motivo quando relevante e nova data.',state:'AGENDADO'};
  case 'noshow': return {answer:`${g}vi que não conseguimos realizar sua avaliação. Quero primeiro entender se aconteceu algum imprevisto.`,question:'Está tudo bem por aí?',action:'RECUPERAR NO-SHOW',register:'Registrar motivo da falta e próximo passo.',state:'BLOQUEADO'};
  case 'price-block': return {answer:`${g}entendo. Antes de tratar o valor como único motivo, vale entender se foi ele que travou sua decisão ou se ficou alguma outra dúvida sobre o tratamento.`,question:'O investimento foi o principal ponto ou existe outra questão que ainda precisa ficar clara?',action:'TRABALHAR BARREIRA',register:'Registrar objeção real, sem presumir que preço é a única barreira.',state:'BLOQUEADO'};
  case 'price': return {answer:`${g}o valor depende do que realmente precisa ser feito, e eu não quero te orientar com uma referência que não tenha relação com o seu caso.`,question:'Hoje estamos falando de um dente, alguns dentes ou uma reabilitação maior?',action:'QUALIFICAR',register:'Registrar que preço apareceu como tema e qual necessidade está sendo considerada.',state:'CONSIDERANDO'};
  case 'fear': return {answer:`${g}é importante você me contar isso. Em vez de tentar minimizar o medo, eu quero entender exatamente o que está deixando você inseguro(a).`,question:'O que mais preocupa você hoje: dor, anestesia, a cirurgia ou alguma experiência anterior?',action:'ENTENDER BARREIRA',register:'Registrar o medo específico e o que ajudaria a pessoa a se sentir mais segura.',state:'BLOQUEADO'};
  case 'bone': return {answer:`${g}receber a informação de que “não tem osso” costuma gerar muita dúvida. Existem diferentes possibilidades, mas não dá para definir a solução certa por mensagem.`,question:'Você chegou a fazer tomografia ou outro exame recentemente?',action:'ORIENTAR + AVALIAÇÃO',register:'Registrar relato de pouca disponibilidade óssea e existência/data de exames.',risk:true,state:'CONSIDERANDO'};
  case 'family': return {answer:`${g}sem problema. É comum a família participar de uma decisão importante como essa.`,question:'O que vocês ainda precisam entender para se sentirem seguros sobre o próximo passo?',action:'APOIAR DECISÃO',register:'Registrar quem participa da decisão e qual informação falta.',state:'CONSIDERANDO'};
  case 'think': return {answer:`${g}tudo bem. Não quero transformar isso em pressão.`,question:'Você prefere um tempo para pensar ou ficou alguma questão específica que eu possa esclarecer antes?',action:'DEFINIR PRÓXIMO CONTATO',register:'Registrar se precisa de tempo, informação ou retorno em data combinada.',state:'ADIANDO'};
  case 'comparison': return {answer:`${g}faz sentido comparar antes de uma decisão importante. O melhor é comparar critérios concretos, sem desqualificar outra clínica.`,question:'O que está pesando mais nessa comparação: valor, estrutura, confiança, prazo ou a proposta de tratamento?',action:'ENTENDER CRITÉRIO',register:'Registrar o critério real de comparação.',state:'CONSIDERANDO'};
  case 'post-eval': return {answer:`${g}depois da avaliação podem surgir dúvidas novas, e eu posso ajudar a organizar isso sem alterar a proposta clínica.`,question:'Sua dúvida agora é sobre o plano apresentado, investimento, organização para começar ou algum ponto clínico?',action:'PÓS-AVALIAÇÃO',register:'Registrar dúvida/barreira e próximo contato.',state:'POS_AVALIACAO'};
  case 'prosthesis': return {answer:`${g}entendi. Como você já usa uma prótese, o mais útil é descobrir o que realmente está pesando na sua rotina.`,question:'O que mais incomoda hoje: mastigação, movimento, conforto, segurança ou aparência?',action:'QUALIFICAR',register:'Registrar principal incômodo e objetivo pessoal.',state:'CONSIDERANDO'};
  case 'one-tooth': return {answer:`${g}entendi. Para orientar sem assumir um tratamento antes da avaliação, vale entender há quanto tempo aconteceu e o impacto hoje.`,question:'Faz quanto tempo que você perdeu esse dente?',action:'QUALIFICAR',register:'Registrar tempo aproximado e principal impacto.',state:'CONSIDERANDO'};
  case 'many-teeth': return {answer:`${g}entendi. Quando faltam vários dentes, a situação atual e a forma como isso afeta a rotina ajudam a direcionar a avaliação.`,question:'Hoje você usa alguma prótese para substituir esses dentes ou está sem eles?',action:'QUALIFICAR',register:'Registrar situação funcional e objetivo principal.',state:'CONSIDERANDO'};
  case 'clinical': {const f=faqMatch(text);return {answer:f?.answer||`${g}essa é uma dúvida importante. Posso explicar de forma geral, mas a resposta para o seu caso depende da avaliação do dentista.`,question:f?.urgent?'':'Se quiser, me diga qual parte dessa dúvida mais preocupa você para eu organizar o próximo passo.',action:f?.urgent?'ESCALAR CLÍNICO':'ORIENTAR',register:'Registrar a dúvida clínica quando ela influenciar a decisão.',risk:true,source:'Base clínica segura',state:'CONSIDERANDO'};}
  case 'hello': return {answer:`Oi${name?', '+firstName(name):''}! Seja bem-vindo(a) à Ultra.`,question:'O que fez você procurar a gente hoje?',action:'ENTENDER',register:'Registrar interesse assim que ficar claro.',state:'EXPLORANDO'};
  default: return {answer:`${g}quero ter certeza de que entendi antes de te orientar.`,question:'O que você gostaria de entender ou resolver hoje?',action:'PEDIR CONTEXTO',register:'Ainda não há contexto suficiente para registrar uma barreira.',state:'EXPLORANDO'};
 }
}

export function inferKnown(text){const n=normalize(text),out=[];if(n.includes('dentadura')||n.includes('protese'))out.push('Já usa ou menciona prótese.');if(n.includes('medo')||n.includes('pavor')||n.includes('anestesia'))out.push('Existe medo/insegurança declarado.');if(n.includes('osso'))out.push('Menciona condição óssea ou informação prévia sobre osso.');if(n.includes('filha')||n.includes('filho')||n.includes('esposa')||n.includes('marido')||n.includes('mae')||n.includes('pai'))out.push('Há familiar no contexto.');if(n.includes('preco')||n.includes('valor'))out.push('Preço apareceu como tema.');return out}
export function detectMotivation(text){const n=normalize(text);const map=[['voltar a comer','Voltar a comer/mastigar melhor'],['mastigar','Melhorar mastigação'],['sorrir','Sorrir com mais segurança'],['vergonha','Reduzir constrangimento ao sorrir'],['resolver','Resolver o problema'],['nao quero mais dentadura','Deixar de depender da dentadura']];return map.find(([k])=>n.includes(k))?.[1]||''}
export function analyze(text,{name='',agent=''}={}){const intent=routeIntent(text);const base=scenarioResponse(intent,text,name);const known=inferKnown(text);const motivation=detectMotivation(text);const safety=[];if(base.risk)safety.push('Existe limite clínico: não diagnosticar, prescrever, prometer resultado ou definir tratamento individual por mensagem.');if((base.answer+' '+base.question).length>700)safety.push('Resposta longa: reduzir antes de enviar.');return {id:`a_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,createdAt:new Date().toISOString(),raw:text,name,agent,intent:intent.id,intentLabel:intent.label,confidence:intent.confidence,state:base.state||'EXPLORANDO',answer:base.answer,question:base.question,action:base.action,register:base.register,known,motivation,source:base.source||'',safety}}
